# Generated by Django 5.1.5 on 2025-02-06 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bull_id', models.CharField(max_length=20, unique=True)),
                ('breeding_value', models.IntegerField()),
                ('phenotype_1', models.IntegerField()),
                ('phenotype_2', models.IntegerField()),
                ('phenotype_3', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cow_id', models.CharField(max_length=20, unique=True)),
                ('bull', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offspring', to='myapp.bull')),
                ('great_grandfather', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='great_grandchildren', to='myapp.bull')),
                ('maternal_grandfather', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maternal_grandchildren', to='myapp.bull')),
            ],
        ),
    ]
