# Generated by Django 5.1.5 on 2025-02-18 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bull',
            name='breeding_value',
        ),
        migrations.RemoveField(
            model_name='bull',
            name='bull_id',
        ),
        migrations.RemoveField(
            model_name='bull',
            name='phenotype_1',
        ),
        migrations.RemoveField(
            model_name='bull',
            name='phenotype_2',
        ),
        migrations.RemoveField(
            model_name='bull',
            name='phenotype_3',
        ),
        migrations.RemoveField(
            model_name='cow',
            name='bull',
        ),
        migrations.AddField(
            model_name='bull',
            name='birth_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='bull',
            name='identification_number',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='bull',
            name='pta_ccr',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bull',
            name='pta_displaced_abomasum',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bull',
            name='pta_dpr',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bull',
            name='pta_early_first_calving',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bull',
            name='pta_fat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bull',
            name='pta_feed_saved',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bull',
            name='pta_gestation_length',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bull',
            name='pta_hcr',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bull',
            name='pta_heifer_livability',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bull',
            name='pta_ketosis',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bull',
            name='pta_mastitis',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bull',
            name='pta_metritis',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bull',
            name='pta_milk',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bull',
            name='pta_milk_fever',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bull',
            name='pta_productive_life',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bull',
            name='pta_protein',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bull',
            name='pta_residual_feed_intake',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bull',
            name='pta_retained_placenta',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bull',
            name='pta_scs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bull',
            name='registered_name',
            field=models.CharField(default=0, max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name='cow',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cows_father', to='myapp.bull'),
        ),
        migrations.AlterField(
            model_name='cow',
            name='great_grandfather',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cows_great_grandfather', to='myapp.bull'),
        ),
        migrations.AlterField(
            model_name='cow',
            name='maternal_grandfather',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cows_maternal_grandfather', to='myapp.bull'),
        ),
    ]
