# Generated by Django 5.1.5 on 2025-02-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_bull_breeding_value_remove_bull_bull_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bull',
            name='identification_number',
            field=models.CharField(db_index=True, default=0, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='bull',
            name='registered_name',
            field=models.CharField(default=0, max_length=128),
        ),
        migrations.DeleteModel(
            name='Cow',
        ),
    ]
